import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

kejelasanInformasi = ctrl.Antecedent(np.arange(0, 101), 'kejelasan_informasi')
kejelasanPersyaratan = ctrl.Antecedent(np.arange(0, 101), 'kejelasan_persyaratan')
kemampuanPetugas = ctrl.Antecedent(np.arange(0, 101), 'kemampuan_petugas')
ketersediaanSarpras = ctrl.Antecedent(np.arange(0, 101), 'ketersediaan_sarpras')
kepuasanPelayanan = ctrl.Consequent(np.arange(0, 401), 'kepuasan_pelayanan')

def define_input_mf(var):
    var['tidak memuaskan'] = fuzz.trapmf(var.universe, [0, 0, 60, 75])
    var['cukup memuaskan'] = fuzz.trimf(var.universe, [60, 75, 90])
    var['memuaskan'] = fuzz.trapmf(var.universe, [75, 90, 100, 100])

define_input_mf(kejelasanInformasi)
define_input_mf(kejelasanPersyaratan)
define_input_mf(kemampuanPetugas)
define_input_mf(ketersediaanSarpras)

# kepuasanPelayanan [0-400]
kepuasanPelayanan['tidak memuaskan'] = fuzz.trapmf(kepuasanPelayanan.universe, [0, 0, 50, 100])
kepuasanPelayanan['kurang memuaskan'] = fuzz.trimf(kepuasanPelayanan.universe, [50, 100, 175])
kepuasanPelayanan['cukup memuaskan'] = fuzz.trimf(kepuasanPelayanan.universe, [150, 225, 275])
kepuasanPelayanan['memuaskan'] = fuzz.trimf(kepuasanPelayanan.universe, [250, 300, 350]) 
kepuasanPelayanan['sangat memuaskan'] = fuzz.trapmf(kepuasanPelayanan.universe, [325, 375, 400, 400])

# rules1 sampai 81
rule1 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['kurang memuaskan'])
rule2 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule3 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule4 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule5 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule6 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule7 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule8 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule9 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule10 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule11 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule12 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule13 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule14 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule15 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule16 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule17 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule18 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule19 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule20 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule21 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule22 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule23 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule24 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule25 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule26 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule27 = ctrl.Rule(kejelasanInformasi['tidak memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule28 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule29 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule30 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule31 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule32 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule33 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule34 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule35 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule36 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule37 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule38 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule39 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule40 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule41 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule42 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule43 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule44 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule45 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule46 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule47 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule48 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule49 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule50 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule51 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule52 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule53 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule54 = ctrl.Rule(kejelasanInformasi['cukup memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule55 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule56 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule57 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule58 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule59 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule60 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule61 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule62 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule63 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['tidak memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule64 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['cukup memuaskan'])
rule65 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule66 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['memuaskan'])
rule67 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule68 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule69 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule70 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule71 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule72 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['cukup memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule73 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule74 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['memuaskan'])
rule75 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['tidak memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule76 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['memuaskan'])
rule77 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule78 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['cukup memuaskan'] & ketersediaanSarpras['memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule79 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule80 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['tidak memuaskan'], kepuasanPelayanan['sangat memuaskan'])
rule81 = ctrl.Rule(kejelasanInformasi['memuaskan'] & kejelasanPersyaratan['memuaskan'] & kemampuanPetugas['memuaskan'] & ketersediaanSarpras['cukup memuaskan'], kepuasanPelayanan['sangat memuaskan'])

kepuasanControl = ctrl.ControlSystem([rule1, rule2, rule13, rule14, rule5, rule6, rule7, rule8, rule9, rule10, rule11, rule12, rule13, rule14, rule15, rule16, rule17, rule18, rule19, rule20, rule21, rule22, rule23, rule24, rule25, rule26, rule27, rule28, rule29, rule30, rule31, rule32, rule33, rule34, rule35, rule36, rule37, rule38, rule39, rule40, rule41, rule42, rule43, rule44, rule45, rule46, rule47, rule48, rule49, rule50, rule51, rule52, rule53, rule54, rule55, rule56, rule57, rule58, rule59, rule60, rule61, rule62, rule63, rule64, rule65, rule66, rule67, rule68, rule69, rule70, rule71, rule72, rule73, rule74, rule75, rule76, rule77, rule78, rule79, rule80, rule81])
kepuasanSimulasi = ctrl.ControlSystemSimulation(kepuasanControl)

kepuasanSimulasi.input['kejelasan_informasi'] = 80
kepuasanSimulasi.input['kejelasan_persyaratan'] = 60
kepuasanSimulasi.input['kemampuan_petugas'] = 50
kepuasanSimulasi.input['ketersediaan_sarpras'] = 90

kepuasanSimulasi.compute()

print("Nilai Kepuasan Pelayanan: ", round(kepuasanSimulasi.output['kepuasan_pelayanan'], 2))
kepuasanPelayanan.view(sim=kepuasanSimulasi)
plt.show()